version: "3.7"
services:
  app:
    build: ./
    container_name: app
    ports:
      - "3002:3002"
    depends_on:
      - postgres_db
    networks:
      - underground
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres_db:5432/stori?connect_timeout=300
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stori
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - underground
networks:
  underground:
